{
 "title": "AWS DocumentDB Basic",
 "description": "Visualize AWS DocumentDB metrics.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "region", "query": "regions()" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": "dimension_values($region,AWS/DocDB,CPUUtilization,DBClusterIdentifier)"
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": "dimension_values($region,AWS/DocDB,CPUUtilization,DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPUUtilization",
   "type": "timeseries",
   "description": "The percentage of CPU used by an instance.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "description": "The number of connections open on an instance taken at a one-minute frequency.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "description": "The amount of available random access memory, in bytes.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Free Local Storage",
   "type": "timeseries",
   "description": "This metric reports the amount of storage available to each instance for temporary tables and logs. This value depends on the instance class. You can increase the amount of free storage space for an instance by choosing a larger instance class for your instance.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "FreeLocalStorage",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Engine Uptime",
   "type": "timeseries",
   "description": "The amount of time, in seconds, that the instance has been running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "EngineUptime",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "DB Instance ReplicaLag",
   "type": "timeseries",
   "description": "The amount of lag, in milliseconds, when replicating updates from the primary instance to a replica instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DBInstanceReplicaLag",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "description": "The average amount of time taken per disk I/O operation.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "ReadLatency",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "description": "The average amount of time, in milliseconds, taken per disk I/O operation.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "WriteLatency",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "description": "The number of concurrent write requests to the distributed storage volume.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Opcounters Query",
   "type": "timeseries",
   "description": "The number of queries issued in a one-minute period.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "OpcountersQuery",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Opcounters Insert",
   "type": "timeseries",
   "description": "The number of insert operations issued in a one-minute period.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "OpcountersInsert",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Opcounters Update",
   "type": "timeseries",
   "description": "The number of update operations issued in a one-minute period.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "OpcountersUpdate",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Opcounters Delete",
   "type": "timeseries",
   "description": "The number of delete operations issued in a one-minute period.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "OpcountersDelete",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Opcounters Getmore",
   "type": "timeseries",
   "description": "The number of getmores issued in a one-minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "OpcountersGetmore",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Opcounters Command",
   "type": "timeseries",
   "description": "The number of commands issued in a one-minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "OpcountersCommand",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Documents Returned",
   "type": "timeseries",
   "description": "The number of returned documents in a one-minute period.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DocumentsReturned",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Documents Inserted",
   "type": "timeseries",
   "description": "The number of inserted documents in a one-minute period.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DocumentsInserted",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Documents Updated",
   "type": "timeseries",
   "description": "The number of updated documents in a one-minute period.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DocumentsUpdated",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Documents Deleted",
   "type": "timeseries",
   "description": "The number of deleted documents in a one-minute period.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DocumentsDeleted",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Transactions Started",
   "type": "timeseries",
   "description": "The number of transactions started on an instance in a one-minute period.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "TransactionsStarted",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Transactions Committed",
   "type": "timeseries",
   "description": "The number of transactions committed on an instance in a one-minute period.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "TransactionsCommitted",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Transactions Aborted",
   "type": "timeseries",
   "description": "The number of transactions aborted on an instance in a one-minute period.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "TransactionsAborted",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "TTLDeletedDocuments",
   "type": "timeseries",
   "description": "The number of documents deleted by a TTLMonitor in a one-minute period.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "TTLDeletedDocuments",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Low Mem Num Operations Throttled",
   "type": "timeseries",
   "description": "The number of requests that are throttled due to low available memory in a one-minute period.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "LowMemNumOperationsThrottled",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Low Mem Throttle Queue Depth",
   "type": "timeseries",
   "description": "The queue depth for requests that are throttled due to low available memory taken at a one-minute frequency.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "LowMemThrottleQueueDepth",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Low Mem Throttle Max Queue Depth",
   "type": "timeseries",
   "description": "The maximum queue depth for requests that are throttled due to low available memory in a one-minute period.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "LowMemThrottleMaxQueueDepth",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Index Buffer Cache HitRatio",
   "type": "timeseries",
   "description": "The percentage of index requests that are served by the buffer cache. You might see a spike greather than 100% for the metric right after you drop an index, collection or database. This will automatically be corrected after 60 seconds. This limitation will be fixed in a future patch update.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "IndexBufferCacheHitRatio",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Buffer Cache HitRatio",
   "type": "timeseries",
   "description": "The percentage of requests that are served by the buffer cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "BufferCacheHitRatio",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Cursor & Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Database Cursors",
   "type": "timeseries",
   "description": "The number of cursors open on an instance taken at a one-minute frequency.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DatabaseCursors",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database Cursors Max",
   "type": "timeseries",
   "description": "The maximum number of open cursors on an instance in a one-minute period.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DatabaseCursorsMax",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Database Cursors TimedOut",
   "type": "timeseries",
   "description": "The number of cursors that timed out in a one-minute period.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "DatabaseCursorsTimedOut",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Transactions Open",
   "type": "timeseries",
   "description": "The number of transactions open on an instance taken at a one-minute frequency.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "TransactionsOpen",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Transactions Open Max",
   "type": "timeseries",
   "description": "The maximum number of transactions open on an instance in a one-minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "TransactionsOpenMax",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "description": "The average number of bytes read from disk per second.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "description": "The average number of disk read I/O operations per second. Amazon DocumentDB reports read and write IOPS separately, and on one-minute intervals.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "description": "The average number of bytes written to disk per second.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "description": "The average number of disk write I/O operations per second. When used on a cluster level, WriteIOPs are evaluated across all instances in the cluster. Read and write IOPS are reported separately, on 1-minute intervals.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Network Receive Throughput",
   "type": "timeseries",
   "description": "The amount of network throughput, in bytes per second, received from clients by each instance in the cluster. This throughput doesn't include network traffic between instances in the cluster and the cluster volume.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Network Transmit Throughput",
   "type": "timeseries",
   "description": "The amount of network throughput, in bytes per second, sent to clients by each instance in the cluster. This throughput doesn't include network traffic between instances in the cluster and the cluster volume.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "description": "The amount of network throughput, in bytes per second, both received from and transmitted to clients by each instance in the Amazon DocumentDB cluster. This throughput doesn't include network traffic between instances in the cluster and the cluster volume.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$Instance" },
     "metricName": "NetworkThroughput",
     "namespace": "AWS/DocDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}