{
 "title": "Amazon CloudWatch Logs",
 "description": "Visualize Amazon CloudWatch Log based metrics",
 "tags": [
  "Amazon",
  "AWS",
  "CloudWatch",
  "Logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  {
   "title": "Incoming log events [count/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingLogEvents\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Incoming bytes [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingBytes\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Delivery errors [count]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "metricName": "DeliveryErrors",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Delivery throttling [count]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "metricName": "DeliveryThrottling",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Forwarded log events [count/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"ForwardedLogEvents\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "ForwardedLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Forwarded bytes [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"ForwardedBytes\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "ForwardedBytes",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "For more information about the available metrics for Amazon CloudWatch Logs, please visit the [CloudWatch documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch-Logs-Monitoring-CloudWatch-Metrics.html)."
   },
   "targets": [
    { "region": "default", "statistic": "Average" }
   ]
  }
 ]
}