{
 "title": "MSK Overview production (all topics)",
 "description": "Prometheus monitoring for MSK cluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumtion Lag per every consumer group",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_group_ConsumerLagMetrics_Value{name=~\"EstimatedTimeLag\", topic=~\"$topic\"}",
     "legendFormat": "{{ groupId}}"
    }
   ]
  },
  {
   "title": "Production Rate / 5m",
   "type": "graph",
   "description": "whether we're ingesting data to partition",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, partition) (increase(kafka_log_Log_Value{name=\"LogEndOffset\", topic=~\"$topic\"}[5m])) \n",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  {
   "title": "POD \"consumer\" counter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\",namespace=\"production\",pod=~\"thread-service.*\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Request Rate per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_RequestMetrics_Count{name=\"RequestsPerSec\", request=~\"Produce|FetchConsumer|FetchFollower\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}